{
 "title": "MAXONROW",
 "description": "Real time information of Node",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "StateBlockProicessingTime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_state_block_processing_time_bucket"
    }
   ]
  },
  {
   "title": "Go Memory  Allocated Bytes ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "GO Heap Objects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_heap_objects" }
   ]
  },
  {
   "title": "Byzantine Validator",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators"
    }
   ]
  },
  {
   "title": " Valid  Transaction",
   "type": "gauge",
   "description": "Display Valid Transaction",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "targets": [
    { "expr": "tendermint_consensus_total_txs" }
   ]
  },
  {
   "title": "Validator Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power"
    }
   ]
  },
  {
   "title": "VALIDATOR",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "tendermint_consensus_validators"
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "gauge",
   "description": "Display Number of transaction created",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "targets": [
    { "expr": "tendermint_consensus_num_txs" }
   ]
  },
  {
   "title": "Consensus Block Size",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes"
    }
   ]
  },
  {
   "title": "Block Processing Time count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_state_block_processing_time_count"
    }
   ]
  },
  {
   "title": "BlockHeight",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "targets": [
    { "expr": "tendermint_consensus_height" }
   ]
  },
  {
   "title": "Block Processing Time Bucket",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "tendermint_state_block_processing_time_bucket"
    }
   ]
  },
  {
   "title": "GO CPU Fraction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_gc_cpu_fraction" }
   ]
  },
  {
   "title": "Go Memory status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "targets": [
    { "expr": "go_memstats_sys_bytes" }
   ]
  },
  {
   "title": "Go Routine",
   "type": "gauge",
   "description": "Number of running go routines",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Consensus Round",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "targets": [
    { "expr": "tendermint_consensus_rounds" }
   ]
  },
  {
   "title": "Go Threads",
   "type": "gauge",
   "description": "Number of threads running",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "targets": [
    { "expr": "go_threads" }
   ]
  },
  {
   "title": "Missing Validator Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power"
    }
   ]
  },
  {
   "title": "Missing Validator",
   "type": "gauge",
   "description": "Gives information of validator offline",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators"
    }
   ]
  },
  {
   "title": "Block Interval",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds"
    }
   ]
  },
  {
   "title": "LatestBlock Height",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "targets": [
    { "expr": "tendermint_mempool_size" }
   ]
  }
 ]
}